### ISSUE TITLE
problem with ver2.0_ardIDE

### ISSUE THREAD

**Issue by AlirezaAbdiyan** [amiravni/MSGEQ7_ESP8266_WS2812#1]
I upload MSGEQ7.ino and webPage in a ESP8266-12E module but I can't run setting webpage!
Please help me.
Thanks.

**Comment by amiravni** [comment]
Hi, 
The webPage is not on the esp, it is uploaded to your server/computer and run from there

**Comment by AlirezaAbdiyan** [comment]
Hi
I will check it.
Thanks.

**Comment by gnkarn** [comment]
could you please explain how to copy the code generated with the RIB.
i have it working but could not find a way to make use of the code generated, not exporting, now copying or pasting, no way to save it to a file , could it be that the RIB code got broken as it become old ?
in this case do you know any other equivalent tool,? thank you

**Comment by amiravni** [comment]
Both export and copy/paste of the code works for me. Do you use Chrome? Maybe try to open a new project (on the "Home" button).

If nothing works try to send them an email or take my code and change it

**Comment by gnkarn** [comment]
Thanks for your answer.

Yes im using chrome , on a mac
I included the option for chrome to be able to open files and use cookies , but nothing change .
No way to copy or save anything .

**Comment by amiravni** [comment]
Hmm.. Interesting... I use Windows so I don't really know how it works on Mac

**Comment by gnkarn** [comment]
I tryed in Windows and was able to make it work  from the site , not offline , but the Tizen gadgets do not appear , so no color picker ,  offline Tizen works but can't save or copy the files, . .. 
It seams that the online rib is incomplete, and that the offline version needs some configuration that may not be enough detailed ...

**Comment by amiravni** [comment]
After you download your code to the computer try to compare the HTML header with my HTML file. I think I updated one of the jQuery libraries because it stopped working on Chrome after one of its updates (Did work on other browsers though)
